name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      working-directory: ./frontend
      run: |
        docker build . --file Dockerfile.dev --tag mahidharbandaru/frontend
        docker run mahidharbandaru/frontend npm run coverage
